<?php

namespace Database\Seeders;

use App\Models\ChooseBusiness;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ChooseBusinessSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        ChooseBusiness::insert([
            [
                'id'          => 1,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>We provide support services specifically designed for skilled trade professionals. Whether you\'re a plumber, electrician, carpenter, or HVAC technician, our team matches you with Pros that understands your industry\'s unique needs and challenges ensuring that you receive tailored solutions that align with your business goals.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '02', '58'),
                'updated_at'  => Carbon::create('2024', '06', '24', '12', '05', '30'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 2,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Comprehensive Support',
                'description' => '<p>From administrative assistance to bookkeeping, legal advice to marketing strategies, we offer comprehensive support services to streamline your business operations. Instead of juggling multiple service providers, you can rely on us as your one-stop shop for all your support needs.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '05', '26'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '40'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 3,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Cost-Effective Solutions',
                'description' => '<p>Outsourcing support services to Trade Support Pros can be a cost-effective alternative to hiring full-time staff or managing tasks internally. By paying for only the services you need when you need them, you can optimize your budget and allocate resources more efficiently.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '06', '03'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '43'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 4,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>As a skilled trade professional, your time is best spent focusing on your core business activities. By delegating administrative tasks, bookkeeping, and other support functions to us, you can reclaim valuable time and energy to invest in growing your business and serving your clients.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '06', '36'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '47'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 5,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>We provide support services specifically designed for skilled trade professionals. Whether you\'re a plumber, electrician, carpenter, or HVAC technician, our team matches you with Pros that understands your industry\'s unique needs and challenges ensuring that you receive tailored solutions that align with your business goals.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '07', '01'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '50'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 6,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>We provide support services specifically designed for skilled trade professionals. Whether you\'re a plumber, electrician, carpenter, or HVAC technician, our team matches you with Pros that understands your industry\'s unique needs and challenges ensuring that you receive tailored solutions that align with your business goals.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '07', '31'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '52'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 7,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>We provide support services specifically designed for skilled trade professionals. Whether you\'re a plumber, electrician, carpenter, or HVAC technician, our team matches you with Pros that understands your industry\'s unique needs and challenges ensuring that you receive tailored solutions that align with your business goals.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '07', '59'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '12', '56'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 8,
                'type'        => 'pro',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Tailored Expertise',
                'description' => '<p>We provide support services specifically designed for skilled trade professionals. Whether you\'re a plumber, electrician, carpenter, or HVAC technician, our team matches you with Pros that understands your industry\'s unique needs and challenges ensuring that you receive tailored solutions that align with your business goals.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '08', '26'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '00'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 9,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Varied Opportunities',
                'description' => '<p>As a service professional with Trade Support Pros, you\'ll have many opportunities to collaborate with skilled tradespersons. From providing legal advice and financial services to offering administrative support and marketing assistance, diverse roles are available to suit your skills and interests.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '09', '12'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '02'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 10,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Client Base Expansion',
                'description' => '<p>Partnering with skilled tradespersons opens new avenues for expanding your client base. You\'ll have the opportunity to connect with tradespersons\' existing clients and networks, allowing you to reach a broader audience and grow your business.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '09', '41'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '05'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 11,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Holistic Solutions',
                'description' => '<p>By working with skilled tradespersons, you\'ll have the chance to offer solutions to clients. Whether assisting with contract negotiations, providing financial planning services, or offering legal guidance, you can complement the tradespersons\' expertise with your own, delivering comprehensive support that adds value to client projects</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '10', '12'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '08'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 12,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Collaborative Environment',
                'description' => '<p>Trade Support Pros fosters a collaborative environment where service professionals and tradespersons work together to achieve common goals. You\'ll be able to collaborate on projects, share knowledge and resources, and build mutually beneficial partnerships that contribute to collective success.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '10', '41'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '11'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 13,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Flexibility and Independence',
                'description' => '<p>As a service professional with Trade Support Pros, you\'ll enjoy flexibility and independence in your work. You can choose the projects you want to work on, schedule, and manage your workload according to your preferences, allowing you to achieve a healthy work-life balance.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '11', '10'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '14'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 14,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Professional Development',
                'description' => '<p>Trade Support Pros is committed to supporting the professional development of its team members. You\'ll have access to training opportunities, workshops, and resources to enhance your skills and stay updated on industry trends, ensuring you\'re equipped to deliver top-notch service to clients.</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '11', '42'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '17'),
                'deleted_at'  => null,
            ],
            [
                'id'          => 15,
                'type'        => 'trade',
                'image'       => 'frontend/images/feature-icon.png',
                'title'       => 'Stability and Growth',
                'description' => '<p>Joining Trade Support Pros provides stability and opportunities for growth in your career. You\'ll be part of a reputable organization with a strong presence in the trade industry, offering long-term prospects for advancement and success</p>',
                'status'      => 'active',
                'created_at'  => Carbon::create('2024', '06', '24', '12', '12', '13'),
                'updated_at'  => Carbon::create('2024', '06', '24', '18', '13', '20'),
                'deleted_at'  => null,
            ],
        ]);
    }
}
