<?php

namespace Database\Seeders;

use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        $options = [
            [
                'id'          => 1,
                'question_id' => 1,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:48:57',
                'updated_at'  => '2024-06-19 20:48:57',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 2,
                'question_id' => 1,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:48:57',
                'updated_at'  => '2024-06-19 20:48:57',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 3,
                'question_id' => 3,
                'option_text' => 'Full-Time',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:53:07',
                'updated_at'  => '2024-06-19 20:53:07',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 4,
                'question_id' => 3,
                'option_text' => 'Part-Time',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:53:07',
                'updated_at'  => '2024-06-19 20:53:07',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 5,
                'question_id' => 3,
                'option_text' => 'Temporary',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:53:07',
                'updated_at'  => '2024-06-19 20:53:07',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 6,
                'question_id' => 3,
                'option_text' => 'Project Based',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:53:07',
                'updated_at'  => '2024-06-19 20:53:07',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 7,
                'question_id' => 3,
                'option_text' => 'Not Sure',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:53:07',
                'updated_at'  => '2024-06-19 20:53:07',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 8,
                'question_id' => 2,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:54:24',
                'updated_at'  => '2024-06-19 20:54:24',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 9,
                'question_id' => 2,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:54:24',
                'updated_at'  => '2024-06-19 20:54:24',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 10,
                'question_id' => 4,
                'option_text' => '$0-1000',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:57:23',
                'updated_at'  => '2024-06-19 20:57:23',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 11,
                'question_id' => 4,
                'option_text' => '$1001-5000',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:57:23',
                'updated_at'  => '2024-06-19 20:57:23',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 12,
                'question_id' => 4,
                'option_text' => '$5001-10000',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:57:23',
                'updated_at'  => '2024-06-19 20:57:23',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 13,
                'question_id' => 4,
                'option_text' => '$10001 and up',
                'status'      => 'active',
                'created_at'  => '2024-06-19 20:57:23',
                'updated_at'  => '2024-06-19 20:57:23',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 14,
                'question_id' => 5,
                'option_text' => 'Reliability',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 15,
                'question_id' => 5,
                'option_text' => 'Attention To Detail',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 16,
                'question_id' => 5,
                'option_text' => 'Communication Skills',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 17,
                'question_id' => 5,
                'option_text' => 'Problem-Solving Skills',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 18,
                'question_id' => 5,
                'option_text' => 'Knowledge of Industry Standards',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 19,
                'question_id' => 5,
                'option_text' => 'Responsiveness',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 20,
                'question_id' => 5,
                'option_text' => 'Industry Knowledge',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 21,
                'question_id' => 5,
                'option_text' => 'Years of Experience',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 22,
                'question_id' => 5,
                'option_text' => 'Other: (Allow Text Entry)',
                'status'      => 'active',
                'created_at'  => '2024-06-19 21:00:00',
                'updated_at'  => '2024-06-19 21:00:00',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 23,
                'question_id' => 7,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:26:51',
                'updated_at'  => '2024-06-20 02:26:51',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 24,
                'question_id' => 7,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:26:51',
                'updated_at'  => '2024-06-20 02:26:51',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 25,
                'question_id' => 8,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:28:01',
                'updated_at'  => '2024-06-20 02:28:01',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 26,
                'question_id' => 8,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:28:01',
                'updated_at'  => '2024-06-20 02:28:01',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 27,
                'question_id' => 10,
                'option_text' => '.',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:31:51',
                'updated_at'  => '2024-06-20 02:31:51',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 28,
                'question_id' => 12,
                'option_text' => '.',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:32:14',
                'updated_at'  => '2024-06-20 02:32:14',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 29,
                'question_id' => 21,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 30,
                'question_id' => 21,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 31,
                'question_id' => 25,
                'option_text' => 'Yes',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 32,
                'question_id' => 25,
                'option_text' => 'No',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 33,
                'question_id' => 26,
                'option_text' => 'Full-Time',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 34,
                'question_id' => 26,
                'option_text' => 'Part-Time',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 35,
                'question_id' => 26,
                'option_text' => 'Temporary',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 36,
                'question_id' => 26,
                'option_text' => 'Project Based',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 37,
                'question_id' => 26,
                'option_text' => 'Not Sure',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 38,
                'question_id' => 27,
                'option_text' => '$0-1000',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 39,
                'question_id' => 27,
                'option_text' => '$1001-5000',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 40,
                'question_id' => 27,
                'option_text' => '$5001-10000',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 41,
                'question_id' => 27,
                'option_text' => '$10001 and up',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 42,
                'question_id' => 28,
                'option_text' => 'Reliability',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 43,
                'question_id' => 28,
                'option_text' => 'Attention To Detail',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 44,
                'question_id' => 28,
                'option_text' => 'Communication Skills',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 45,
                'question_id' => 28,
                'option_text' => 'Problem-Solving Skills',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 46,
                'question_id' => 28,
                'option_text' => 'Knowledge of Industry Standards',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 47,
                'question_id' => 28,
                'option_text' => 'Responsiveness',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 48,
                'question_id' => 28,
                'option_text' => 'Industry Knowledge',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 49,
                'question_id' => 28,
                'option_text' => 'Years of Experience',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 50,
                'question_id' => 28,
                'option_text' => 'Other: (Allow Text Entry)',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
            [
                'id'          => 51,
                'question_id' => 28,
                'option_text' => 'Full-Time',
                'status'      => 'active',
                'created_at'  => '2024-06-20 02:46:30',
                'updated_at'  => '2024-06-20 02:46:30',
                'deleted_at'  => NULL,
            ],
        ];

        // Insert data into the database
        foreach ($options as $optionData) {
            Option::updateOrCreate(['id' => $optionData['id']], $optionData);
        }
    }
}
