<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        $questions = [
            [
                'id'            => 1,
                'category'      => 'pro',
                'question_text' => 'Do you have experience working in the trade industry or similar fields as indicated? It is okay if you don\'t; we just want to know your experience level for your match',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-19 20:41:07',
                'updated_at'    => '2024-06-19 20:48:42',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 2,
                'category'      => 'pro',
                'question_text' => 'Are you proficient in using online software and comfortable uploading/downloading and communicating through our Trade Pros Portal?',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-19 20:50:10',
                'updated_at'    => '2024-06-19 20:50:10',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 3,
                'category'      => 'pro',
                'question_text' => 'What are your Pro-time Preferences?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-19 20:52:12',
                'updated_at'    => '2024-06-19 20:52:12',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 4,
                'category'      => 'pro',
                'question_text' => 'What are your fees for professional services for this Trade?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-19 20:56:18',
                'updated_at'    => '2024-06-19 20:56:18',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 5,
                'category'      => 'pro',
                'question_text' => 'What are the most important qualities when looking to work with a Tradesman Partner?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-19 20:58:11',
                'updated_at'    => '2024-06-19 20:58:11',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 6,
                'category'      => 'pro',
                'question_text' => 'What are your Pro-time Preferences?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:25:22',
                'updated_at'    => '2024-06-20 02:25:22',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 7,
                'category'      => 'pro',
                'question_text' => 'How do you prioritize tasks and maintain organization in a busy office setting?',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:26:36',
                'updated_at'    => '2024-06-20 02:26:36',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 8,
                'category'      => 'pro',
                'question_text' => 'How do you stay up-to-date with industry regulations and best practices in your chosen trade industry?',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:27:46',
                'updated_at'    => '2024-06-20 02:27:46',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 9,
                'category'      => 'pro',
                'question_text' => 'Do you agree references to Trade Support Pros and agree to a background check?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:28:50',
                'updated_at'    => '2024-06-20 02:28:50',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 10,
                'category'      => 'pro',
                'question_text' => 'I agree to provide references to Trade Support Pros',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:29:22',
                'updated_at'    => '2024-06-20 02:29:22',
                'deleted_at'    => '2024-08-24 13:20:27',
            ],
            [
                'id'            => 11,
                'category'      => 'pro',
                'question_text' => 'Upload file',
                'type'          => 'file',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:29:37',
                'updated_at'    => '2024-06-20 02:29:37',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 12,
                'category'      => 'pro',
                'question_text' => 'I authorize Trade Support Pros to do a comprehensive background check. Trade Support Pros is an equal opportunity employer, and all results are confidential',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:30:44',
                'updated_at'    => '2024-06-20 02:30:44',
                'deleted_at'    => '2024-08-24 13:21:32',
            ],
            [
                'id'            => 13,
                'category'      => 'pro',
                'question_text' => 'How do you stay informed about tax law and regulation changes that may impact trade business?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:33:20',
                'updated_at'    => '2024-06-20 02:33:20',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 14,
                'category'      => 'pro',
                'question_text' => 'What strategies do you use to help trade business reduce tax liabilities and maximize deductions?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:34:11',
                'updated_at'    => '2024-06-20 02:34:11',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 15,
                'category'      => 'pro',
                'question_text' => 'How do you help trade business navigate legal issues like contracts, licensing, insurance, and compliance?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:37:30',
                'updated_at'    => '2024-06-20 02:37:30',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 16,
                'category'      => 'pro',
                'question_text' => 'Have you created content for trade business before, and can you share examples of your work? (Upload capabilities)',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:40:12',
                'updated_at'    => '2024-06-20 02:40:12',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 17,
                'category'      => 'pro',
                'question_text' => 'How do you research industry trends, keywords, and audience preferences to develop content that resonates with trade professionals?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:41:54',
                'updated_at'    => '2024-06-20 02:41:54',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 18,
                'category'      => 'pro',
                'question_text' => 'What types of content do you specialize in (e.g., blog posts, case studies, whitepapers), and how do you tailor them to the trade industry?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:43:26',
                'updated_at'    => '2024-06-20 02:43:26',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 19,
                'category'      => 'pro',
                'question_text' => 'How do you measure the success of content marketing campaigns for trade business, and what key performance indicators do you track?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:44:24',
                'updated_at'    => '2024-06-20 02:44:24',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 20,
                'category'      => 'pro',
                'question_text' => 'How do you collaborate with trade professionals to create content showcasing their expertise and building trust with their target audience?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:45:32',
                'updated_at'    => '2024-06-20 02:45:32',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 21,
                'category'      => 'pro',
                'question_text' => 'Are you comfortable uploading and downloading documents through our secure Trade Support Portal?',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:46:20',
                'updated_at'    => '2024-06-20 02:46:20',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 22,
                'category'      => 'pro',
                'question_text' => 'Do you agree to provide reference to Trade Support Pros and agree to a background check?',
                'type'          => 'textarea',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:47:22',
                'updated_at'    => '2024-06-20 02:47:22',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 23,
                'category'      => 'pro',
                'question_text' => 'Are you a licensed attorney or paralegal with experience in the trade industry chosen?',
                'type'          => 'file',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:24',
                'updated_at'    => '2024-06-20 02:48:24',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 24,
                'category'      => 'pro',
                'question_text' => 'Upload file',
                'type'          => 'file',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:36',
                'updated_at'    => '2024-06-20 02:48:36',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 25,
                'category'      => 'trade',
                'question_text' => 'Are you comfortable uploading and downloading documents through our secure Trade Support Portal?',
                'type'          => 'radio',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:36',
                'updated_at'    => '2024-06-20 02:48:36',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 26,
                'category'      => 'trade',
                'question_text' => 'Are you proficient in using online software and comfortable uploading/downloading and communicating through our Trade Pros Portal?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:36',
                'updated_at'    => '2024-06-20 02:48:36',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 27,
                'category'      => 'trade',
                'question_text' => 'What are your fees for professional services for this Trade?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:36',
                'updated_at'    => '2024-06-20 02:48:36',
                'deleted_at'    => NULL,
            ],
            [
                'id'            => 28,
                'category'      => 'trade',
                'question_text' => 'What are the most important qualities when looking to work with a Tradesman Partner?',
                'type'          => 'checkbox',
                'status'        => 'active',
                'created_at'    => '2024-06-20 02:48:36',
                'updated_at'    => '2024-06-20 02:48:36',
                'deleted_at'    => NULL,
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
